### ISSUE TITLE
I met an Error: ImportError: cannot import name 'DiagnosticOptions' from 'torch.onnx._internal.exporter'  with torch==2.4.1

### ISSUE THREAD

**Issue by JimXu1989** [NVlabs/FoundationStereo#25]
(foundation_stereo) jim@jim-ROG-Strix-G834JZ-G834JZ:~/Software/FoundationStereo$ python scripts/run_demo.py --left_file ./assets/left.png --right_file ./assets/right.png --ckpt_dir ./pretrained_models/model_best_bp2.pth --out_dir ./test_outputs/
Traceback (most recent call last):
  File "/home/jim/Software/FoundationStereo/scripts/run_demo.py", line 15, in <module>
    from Utils import *
  File "/home/jim/Software/FoundationStereo/scripts/../Utils.py", line 10, in <module>
    import os, sys, time,torch,torchvision,pickle,trimesh,itertools,datetime,imageio,logging,joblib,importlib,argparse
  File "/home/jim/anaconda3/envs/foundation_stereo/lib/python3.9/site-packages/torchvision/__init__.py", line 10, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils  # usort:skip
  File "/home/jim/anaconda3/envs/foundation_stereo/lib/python3.9/site-packages/torchvision/models/__init__.py", line 2, in <module>
    from .convnext import *
  File "/home/jim/anaconda3/envs/foundation_stereo/lib/python3.9/site-packages/torchvision/models/convnext.py", line 8, in <module>
    from ..ops.misc import Conv2dNormActivation, Permute
  File "/home/jim/anaconda3/envs/foundation_stereo/lib/python3.9/site-packages/torchvision/ops/__init__.py", line 1, in <module>
    from ._register_onnx_ops import _register_custom_op
  File "/home/jim/anaconda3/envs/foundation_stereo/lib/python3.9/site-packages/torchvision/ops/_register_onnx_ops.py", line 5, in <module>
    from torch.onnx import symbolic_opset11 as opset11
  File "/home/jim/anaconda3/envs/foundation_stereo/lib/python3.9/site-packages/torch/onnx/__init__.py", line 49, in <module>
    from ._internal.exporter import (  # usort:skip. needs to be last to avoid circular import
ImportError: cannot import name 'DiagnosticOptions' from 'torch.onnx._internal.exporter' (/home/jim/anaconda3/envs/foundation_stereo/lib/python3.9/site-packages/torch/onnx/_internal/exporter/__init__.py)

**Comment by steven-mantis** [comment]
My steps for your information:

1. Install cuda 12.4
2. Delete some dependencies in because we need to manually install some specific version.

```yml
name: foundation_stereo
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - scikit-image
    - omegaconf
    - opencv-contrib-python
    - imgaug
    - ninja
    - timm
    - albumentations
    - jupyterlab
    - scipy
    - joblib
    - scikit-learn
    - ruamel.yaml
    - trimesh
    - pyyaml
    - imageio
    - open3d
    - transformations
    - einops
    - gdown
    - nodejs
```

3. conda env create -f environment.yml
4. conda activate foundation_stereo
5. conda install pytorch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 pytorch-cuda=12.4 -c pytorch -c nvidia
6. pip install [flash_attn-2.7.1.post1+cu124torch2.5.1cxx11abiFALSE-cp39-cp39-win_amd64.whl](https://github.com/kingbri1/flash-attention/releases)
7. pip install [xformers-0.0.28.post3-cp39-cp39-win_amd64.whl](https://download.pytorch.org/whl/cu124/xformers-0.0.28.post3-cp39-cp39-win_amd64.whl#sha256=f2d3d2d5ed96a66bee582bbedaaf53a4933fcfb293140f14c573ec4422cafc26)
8. pip install pandas
9. pip uninstall pillow
10. pip install pillow==11.1.0
11. python scripts/run_demo.py --left_file ./assets/left.png --right_file ./assets/right.png --ckpt_dir ./pretrained_models/model_best_bp2.pth --out_dir ./test_outputs/
12. if you meet "rate limit exceeded" issue, please see here:
https://stackoverflow.com/questions/68901236/urllib-error-httperror-http-error-403-rate-limit-exceeded-when-loading-resnet1
13. Ampere GPU is needed. Make sure your N card is above 30 series.
14. My test platform is windows 10.

![Image](https://github.com/user-attachments/assets/50cda0a8-6080-43fd-8e14-9a6a54c23879)
